;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-visual-line
        company-complete
        completion-at-point
        dabbrev-expand
        end-of-visual-line
        goto-line
        indent-for-tab-command
        kill-region
        kill-visual-line
        paredit-backslash
        paredit-forward-delete
        paredit-open-round
        rjsx-delete-creates-full-tag
        ))

(setq mc/cmds-to-run-once
      '(
        go-guru-definition
        markdown-outdent-or-delete
        ))
